{
  "errors": [
    {
      "test": "unittest.loader._FailedTest.helloworld_tests",
      "traceback": "Traceback (most recent call last):\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\\lib\\unittest\\case.py\", line 592, in run\n    self._callTestMethod(testMethod)\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\\lib\\unittest\\case.py\", line 550, in _callTestMethod\n    method()\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\\lib\\unittest\\loader.py\", line 34, in testFailure\n    raise self._exception\nImportError: Failed to import test module: helloworld_tests\nTraceback (most recent call last):\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\\lib\\unittest\\loader.py\", line 154, in loadTestsFromName\n    module = __import__(module_name)\n  File \"c:\\users\\moina\\documents\\..cpp\\.f2022\\cs 4800\\c2c\\c2c\\src\\unittest\\python\\helloworld_tests.py\", line 4, in <module>\n    from c2c import helloworld\nModuleNotFoundError: No module named 'c2c'\n\n"
    }
  ],
  "failures": [],
  "tests-run": 1
}